GET  http://192.168.168.166:8083/mbc/user/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyYyI6InNlIiwiaWQiOiJpcndhbi5kZXYiLCJleHAiOjE3NTYyMDk4MTF9.Is4xax9gQ_rPZxmLjyjlwmA3y9AyRtqmXcT75Hcn2lI